config/routes.rb
Rails.application.routes.draw do

  root 'groups#index', as: :groups

  post '/search' => 'products#find_products', as: :find_products
  get '/search' => 'products#search', as: :search
  get '/products/:product_slug' => 'products#show', as: :search_result_product
  get '/:group_slug' => 'categories#index', as: :categories
  get '/:group_slug/:category_slug' => 'products#index', as: :products
  get '/:group_slug/:category_slug/:product_slug' => 'products#show', as: :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @group = Browet::CategoryGroup.find_by_slug(params[:group_slug])
    @categories = @group.categories
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Browet::CategoryGroup.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :set_group, only: [:index, :show]
  before_filter :set_category, only: [:index, :show]

  def index
    @products = @category.products
  end

  def show
    @product = Browet::Product.find_by_slug(params[:product_slug])
  end

  def find_products
    @products = Browet::Product.search(params[:query])
    render 'search'
  end

  def search
    @products = []
  end

  private

    def set_category
      @category = Browet::Category.find_by_slug(params[:category_slug]) if params[:category_slug]
    end

    def set_group
      @group = Browet::CategoryGroup.find_by_slug(params[:group_slug]) if params[:group_slug]
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.slim
li{style="margin-left: #{10*depth}px"}
  = link_to category.title, products_path(group_slug: @group.slug, category_slug: category.slug)
  - category.categories.each do |category|
    = render partial: "category", locals: {category: category, depth: depth+1}

app/views/categories/index.html.slim
h2 Categories
h4 
  | Group: 
  = @group.name
ul
  - @categories.each do |category|
    = render partial: "category", locals: {category: category, depth: 0}

app/views/groups/index.html.slim
h2 Groups
ul
  - @groups.each do |group|
    li
      = link_to group.name, categories_path(group_slug: group.slug)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Browet Demo Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to 'Browet demo shop', groups_path %></h1>
<%= link_to "Search", search_path %>
<%= yield %>

</body>
</html>

app/views/products/_product.html.slim
li
  = link_to product.title, product_path(group_slug: @group.slug, category_slug: @category.slug, product_slug: product.slug)

app/views/products/index.html.slim
h2 Products
h4 
  | Group: 
  = link_to @group.name, categories_path(group_slug: @group.slug)
h4 
  | Category: 
  = @category.title
ul
  - @products.each do |product|
    li
      = link_to product.title, product_path(group_slug: @group.slug, category_slug: @category.slug, product_slug: product.slug)

app/views/products/search.html.slim
h2 Products search
= form_tag('/search') do
  = text_field_tag :query
  = submit_tag 'Search!'
- if @products.present?
  h4 Search results
  ul
    - @products.each do |product|
      li
        = link_to product.title, search_result_product_path(product_slug: product.slug)

app/views/products/show.html.slim
h2 = @product.title
- if @group
  h4 
    | Group: 
    = link_to @group.name, categories_path(group_slug: @group.slug)
- if @category
  h4 
    | Category: 
    = link_to @category.title, products_path(group_slug: @group.slug, category_slug: @category.slug)
- @product.pictures.each do |pic|
  = image_tag pic.url, style: "max-width: 200px; max-height: 200px;"
p
  b Brand
  br
  = @product.brand.title
- [:id, :description, :title, :guid, :sku, :mpn, :slug, :availability, :status, :gtin].each do |attr|
  p
    b = attr.to_s.humanize + ":"
    br
    = @product.send(attr)